Доомашнее задание к лекции "Функции"
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}
Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

Задание 1
Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру
Примеры работы:

1.

Введите команду:
p

Введите номер документа:
10006
Результат:
Владелец документа: Аристарх Павлов

2.

Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [21]:
# Данные
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

# Цикл запросов команд

request='Введите команду: '

while True:
    command_request=str(input(request))
    
    if  command_request == 'q':
        break
    elif command_request == 'p': 
        owners(documents) 
    elif command_request == 's':
        shelves(directories)
    elif command_request == 'l':
        all_informations(documents,directories)
    elif command_request == 'ads':   
        add_shelf(directories)
    elif command_request == 'ds':
        delite_shelf(directories)
    else:
        print('Такого запроса не существует')
    


Введите команду: l
№:  2207 876234 , тип:  passport , владелец:  Василий Гупкин , полка хранения:  1
№:  11-2 , тип:  invoice , владелец:  Геннадий Покемонов , полка хранения:  1
№:  10006 , тип:  insurance , владелец:  Аристарх Павлов , полка хранения:  2
Введите команду: p
Введите номер документа владельца: 
10006
Владелец документа:  Аристарх Павлов
Введите команду: s
Введите номер документа владельца: 
11-2
Документ хранится на полке: 1
Введите команду: ds
введите номер полки: 
5
Такая полка не существует. Текущий перечень полок:  ['1', '2', '3']
Введите команду: ds2
Такого запроса не существует
Введите команду: ds
введите номер полки: 
3
Полка удалена. Текущий перечень полок:  ['1', '2']
Введите команду: ads
введите номер полки: 
4
Новая полка создана. Текущий перечень полок:  ['1', '2', '4']
Введите команду: ads
введите номер полки: 
5
Новая полка создана. Текущий перечень полок:  ['1', '2', '4', '5']
Введите команду: ds
введите номер полки: 
1
На полке есть документа, удалите их

In [4]:
# Функция поиcка владельца документа по номеру документа

def owners(documents):
    name=[]
    task=input('Введите номер документа владельца: \n')
    for person in documents:
        if  person['number'] == str(task):
            name=person['name']
        else:
            continue
    if  name == []:
        print('Документ не найден в базе') 
    else:
        print('Владелец документа: ', name)

owners(documents) 

Введите номер документа владельца: 
10006
Владелец документа:  Аристарх Павлов


Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
Примеры работы:

1.

Введите команду:
s

Введите номер документа:
10006
Результат:
Документ хранится на полке: 2

2.

Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [3]:
# Функция поиска полк, на которой находится документ 

def shelves(directories):
    task=str(input('Введите номер документа владельца: \n'))
    number_shelf=''
    for shelfs, number_documents in directories.items():
        for number_document in number_documents: 
            if  task == number_document:
                number_shelf=shelfs
            else:
                continue
    if  number_shelf == '':
        print('Документ не найден в базе') 
    else:
        print('Документ хранится на полке:', number_shelf) 
            
            
shelves(directories)

Введите номер документа владельца: 
11-2
Документ хранится на полке: 1


Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l
Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [20]:
# Функция вывода всех данных

def all_informations(documents,directories):
    for document in documents:
        task=document['number']
        for shelfs, number_documents in directories.items():
            for number_document in number_documents: 
                if  number_document == task:
                    number_shelf=shelfs
                    print('№: ',document['number'],',' ,'тип: ',document['type'],',' ,'владелец: ',document['name'],',' ,'полка хранения: ',number_shelf)
                else:
                    continue

all_informations(documents,directories)           

№:  2207 876234 , тип:  passport , владелец:  Василий Гупкин , полка хранения:  1
№:  11-2 , тип:  invoice , владелец:  Геннадий Покемонов , полка хранения:  1
№:  10006 , тип:  insurance , владелец:  Аристарх Павлов , полка хранения:  2


Пункт 4. Пользователь по команде "ads" может добавить новую полку
Примеры работы:

1.

Введите команду:
ads

Введите номер полки:
10
Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.

2.

Введите команду:
ads

Введите номер полки:
1
Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

In [1]:
# Функция добавления полки

def add_shelf(directories):
    new_shelf = str(input('введите номер полки: \n'))
    if  new_shelf in directories.keys():
        print('Такая полка уже существует. Текущий перечень полок: ', list(directories.keys()))
    else:
        directories[new_shelf]=[]
        print('Новая полка создана. Текущий перечень полок: ', list(directories.keys())) 
        
add_shelf(directories)

введите номер полки: 
2
Такая полка уже существует. Текущий перечень полок:  ['1', '2', '3']


Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
Примеры работы:

1.

Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

2.

Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

3.

Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

In [2]:
# Функция удаления полки

def delite_shelf(directories):
    del_shelf = str(input('введите номер полки: \n'))
    if  del_shelf not in directories.keys():
        print('Такая полка не существует. Текущий перечень полок: ', list(directories.keys()))
    else:
        if  directories[del_shelf]!=[]:
            print('На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: ', list(directories.keys())) 
        else:
            del(directories[del_shelf])
            print('Полка удалена. Текущий перечень полок: ', list(directories.keys()))                                                                                                        
        
delite_shelf(directories)

введите номер полки: 
5
Такая полка не существует. Текущий перечень полок:  ['1', '2', '3']


Задание 2 (необязательное)
Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

Пункт 1. Пользователь по команде "ad" может добавить новый документ в данные
Примеры работы:

1.

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
Результат:

Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
2.

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
Результат:

Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Пункт 2. Пользователь по команде "d" может удалить документ из данных
Примеры работы:

1.

Введите команду:
d

Введите номер документа:
10006
Результат:

Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
2.

Введите команду:
d

Введите номер документа:
123456
Результат:

Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Пункт 3. Пользователь по команде "m" может переместить документ с полки на полку
Примеры работы:

1.

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
Результат:

Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
2.

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

3.

Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
Результат:

Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2